### PR TITLE
Config improvements for package release

### PR DESCRIPTION
**Pull request by philss**
This changes the docs tool and also use a pre-release scheme for the
version of the package.

### CODE REVIEW

**Comment by onno-vos-dev** [comment]
The `path` is different now rather than `edoc` the generated docs are now available in `doc` 

If you change `path: edoc` to `path: doc` in: https://github.com/aws-beam/aws-erlang/blob/5972efea81f7559110b08035b8e473f86217aa76/.github/workflows/build.yml#L49 the build should go through :+1: 

:shipit: apart from that

**Review by onno-vos-dev — CHANGES_REQUESTED** [review]
The path is different now rather than edoc the generated docs are now available in doc

If you change `path: edoc` to `path: doc` in: [aws-erlang/.github/workflows/build.yml](https://github.com/aws-beam/aws-erlang/blob/5972efea81f7559110b08035b8e473f86217aa76/.github/workflows/build.yml#L49) the build should go through :+1: 

:shipit:  apart from that

**Comment by philss** [comment]
> The path is different now rather than edoc the generated docs are now available in doc

Oh, so I need to fix `aws-codegen` before merging this :grimacing: 
There are some modules that won't build docs because of some errors. I will do that next week.

**Comment by onno-vos-dev** [comment]
Closing this @philss as I believe this is now resolved.

**Comment by philss** [comment]
@onno-vos-dev thank you!

**Pull request closed without merging**
